[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

# Clean redirects - one per destination to avoid confusion

# Force HTTPS - redirect all HTTP traffic to HTTPS
[[redirects]]
  from = "http://openfinancecalculators.com/*"
  to = "https://openfinancecalculators.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.openfinancecalculators.com/*"
  to = "https://www.openfinancecalculators.com/:splat"
  status = 301
  force = true

# Remove www redirects to canonical domain
[[redirects]]
  from = "https://www.openfinancecalculators.com/*"
  to = "https://openfinancecalculators.com/:splat"
  status = 301
  force = true

# Canonical domain redirect
[[redirects]]
  from = "https://www.openfinancecalculators.com/"
  to = "https://openfinancecalculators.com/"
  status = 301
  force = true

# Block template literal URLs and search queries
[[redirects]]
  from = "/*${calc.id}*"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/*?q=*"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/*search_term_string*"
  to = "/404.html"
  status = 404
  force = true

# Redirect .html files to clean URLs (canonical)
[[redirects]]
  from = "/about.html"
  to = "/about"
  status = 301
  force = true

[[redirects]]
  from = "/contact.html"
  to = "/contact"
  status = 301
  force = true

[[redirects]]
  from = "/privacy-policy.html"
  to = "/privacy-policy"
  status = 301
  force = true

[[redirects]]
  from = "/terms.html"
  to = "/terms"
  status = 301
  force = true

[[redirects]]
  from = "/calculators.html"
  to = "/calculators"
  status = 301
  force = true

[[redirects]]
  from = "/calculator.html"
  to = "/calculator"
  status = 301
  force = true

# Educators page - no redirect needed since it's already at /educators/

# Remove index.html from root
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

# Contact form success page
[[redirects]]
  from = "/contact-success.html"
  to = "/contact-success"
  status = 301
  force = true

# Ensure favicon is accessible at the conventional root path
[[redirects]]
  from = "/favicon.ico"
  to = "/finance-toolkit-fav/favicon.ico"
  status = 200
  force = true

# Smart redirects for common synonyms and search terms
[[redirects]]
  from = "/loan-calculator"
  to = "/calculators/debt-payoff/"
  status = 301

[[redirects]]
  from = "/snowball-calculator"
  to = "/calculators/debt-payoff/"
  status = 301

[[redirects]]
  from = "/avalanche-calculator"
  to = "/calculators/debt-payoff/"
  status = 301

[[redirects]]
  from = "/debt-calculator"
  to = "/calculators/debt-payoff/"
  status = 301

[[redirects]]
  from = "/investment-calculator"
  to = "/calculators/compound-interest/"
  status = 301

[[redirects]]
  from = "/savings-calculator"
  to = "/calculators/compound-interest/"
  status = 301

[[redirects]]
  from = "/emergency-fund-calculator"
  to = "/calculators/emergency-fund/"
  status = 301

[[redirects]]
  from = "/savings-rate-calculator"
  to = "/calculators/savings-rate/"
  status = 301

# Block access to config directory and template URLs
[[redirects]]
  from = "/config/*"
  to = "/404.html"
  status = 404
  force = true

# 404 page - must be last
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[dev]
  command = "python -m http.server 8000"
  port = 8000
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://cdn.jsdelivr.net;"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/finance-toolkit-fav/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/og/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/ads.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "public, max-age=3600"
